In [1]:

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
df =titanic.loc[:,["age","class","sex","fare","survived"]]
df.head()

    age  class     sex     fare  survived
0  22.0  Third    male   7.2500         0
1  38.0  First  female  71.2833         1
2  26.0  Third  female   7.9250         1
3  35.0  First  female  53.1000         1
4  35.0  Third    male   8.0500         0

In [3]:
pd.pivot_table(
    df,
    index = "class",
    columns= "sex",
    values= "age",
    aggfunc= "mean"
)

sex        female       male
class
First   34.611765  41.281386
Second  28.722973  30.740707
Third   21.750000  26.507589

In [5]:
pd.pivot_table(
    df,
    index = "class",
    columns="sex",
    values="survived",
    aggfunc = ["mean","sum"]
)

            mean              sum
sex       female      male female male
class
First   0.968085  0.368852     91   45
Second  0.921053  0.157407     70   17
Third   0.500000  0.135447     72   47