In [2]:
import pandas as pd


data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')

print(df)

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [3]:
df.to_csv('./data/df_sample.csv')

In [4]:
df.to_csv("./data/df_sample2.csv",index=False) # 인덱스 삭제

In [5]:
# jason 파일로 저장하기

import pandas as pd
df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [8]:
df.to_json("./data/df_sample.json")

In [9]:
# 엑셀 파일로 저장

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [11]:
df.to_excel("./data/df_sample2.xlsx",index=False)